import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../../core/theme/theme_aware_colors.dart';
import '../../data/models/aarti_item.dart';
import '../../data/models/verse_data.dart';
import '../../providers/app_providers.dart';
import '../../widgets/aarti_app_bar.dart';
import '../aarti_detail/aarti_detail_screen.dart';

/// My Personal Collection — saves private Aartis locally via Hive.
class ContributeScreen extends ConsumerStatefulWidget {
  final VoidCallback onOpenDrawer;
  const ContributeScreen({super.key, required this.onOpenDrawer});

  @override
  ConsumerState<ContributeScreen> createState() => _ContributeScreenState();
}

class _ContributeScreenState extends ConsumerState<ContributeScreen> {
  final _deityCtrl = TextEditingController();
  final _titleCtrl = TextEditingController();
  final _devTitleCtrl = TextEditingController();
  final _lyricsCtrl = TextEditingController();
  final _translitCtrl = TextEditingController();
  final _gujaratiCtrl = TextEditingController();
  final _festivalTagsCtrl = TextEditingController();
  bool _showForm = false;
  String? _editingId; // non-null when editing

  @override
  void dispose() {
    _deityCtrl.dispose();
    _titleCtrl.dispose();
    _devTitleCtrl.dispose();
    _lyricsCtrl.dispose();
    _translitCtrl.dispose();
    _gujaratiCtrl.dispose();
    _festivalTagsCtrl.dispose();
    super.dispose();
  }

  void _clearForm() {
    _deityCtrl.clear();
    _titleCtrl.clear();
    _devTitleCtrl.clear();
    _lyricsCtrl.clear();
    _translitCtrl.clear();
    _gujaratiCtrl.clear();
    _festivalTagsCtrl.clear();
    _editingId = null;
  }

  void _populateFormForEdit(AartiItem aarti) {
    _deityCtrl.text = aarti.deity;
    _titleCtrl.text = aarti.title;
    _devTitleCtrl.text = aarti.devanagari;
    _lyricsCtrl.text = aarti.verses.map((v) => v.lines.join('\n')).join('\n\n');
    _translitCtrl.text =
        aarti.verses.map((v) => v.transliteration.join('\n')).join('\n\n');
    _gujaratiCtrl.text =
        aarti.verses.map((v) => v.gujarati.join('\n')).join('\n\n');
    _festivalTagsCtrl.text = aarti.festivalTags.join(', ');
    _editingId = aarti.id;
    setState(() => _showForm = true);
  }

  Future<void> _saveAarti() async {
    final deity = _deityCtrl.text.trim();
    final title = _titleCtrl.text.trim();
    final devanagari = _devTitleCtrl.text.trim();
    final lyrics = _lyricsCtrl.text.trim();
    final translit = _translitCtrl.text.trim();
    final gujarati = _gujaratiCtrl.text.trim();
    final festivalTagsRaw = _festivalTagsCtrl.text.trim();

    if (title.isEmpty || deity.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('Please fill in at least Deity and Title.'),
          backgroundColor: Colors.red.shade700,
          behavior: SnackBarBehavior.floating,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        ),
      );
      return;
    }

    // Build verses from lyrics (split by double newline for verse blocks)
    final verseBlocks = lyrics.isNotEmpty
        ? lyrics
            .split(RegExp(r'\n\s*\n'))
            .where((b) => b.trim().isNotEmpty)
            .toList()
        : <String>[];
    final translitBlocks = translit.isNotEmpty
        ? translit
            .split(RegExp(r'\n\s*\n'))
            .where((b) => b.trim().isNotEmpty)
            .toList()
        : <String>[];
    final gujaratiBlocks = gujarati.isNotEmpty
        ? gujarati
            .split(RegExp(r'\n\s*\n'))
            .where((b) => b.trim().isNotEmpty)
            .toList()
        : <String>[];

    // Parse festival tags (comma separated)
    final festivalTags = festivalTagsRaw.isNotEmpty
        ? festivalTagsRaw.split(',').map((t) => t.trim()).where((t) => t.isNotEmpty).toList()
        : <String>[];

    final verses = verseBlocks.asMap().entries.map((e) {
      final lines =
          e.value.split('\n').where((l) => l.trim().isNotEmpty).toList();
      final tLines = (e.key < translitBlocks.length)
          ? translitBlocks[e.key]
              .split('\n')
              .where((l) => l.trim().isNotEmpty)
              .toList()
          : <String>[];
      final gLines = (e.key < gujaratiBlocks.length)
          ? gujaratiBlocks[e.key]
              .split('\n')
              .where((l) => l.trim().isNotEmpty)
              .toList()
          : <String>[];
      return VerseData(
        label: e.key == 0 ? 'Dhruva Pad' : 'Verse ${e.key}',
        lines: lines,
        transliteration: tLines,
        meanings: const [],
        gujarati: gLines,
      );
    }).toList();

    final aarti = AartiItem(
      id: _editingId ?? '', // will be generated by repo for new ones
      title: title,
      devanagari: devanagari.isNotEmpty ? devanagari : title,
      deity: deity,
      duration: '—',
      versesLabel: '${verses.length} verses',
      verses: verses,
      festivalTags: festivalTags,
    );

    if (_editingId != null) {
      // Delete old and re-save for edit (Hive replaces at same key)
      await ref.read(userAartiProvider.notifier).delete(_editingId!);
    }
    await ref.read(userAartiProvider.notifier).save(aarti);
    _clearForm();
    setState(() => _showForm = false);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(_editingId != null
              ? 'Aarti updated! 🙏'
              : 'Aarti saved to your collection! 🙏'),
          backgroundColor: AppColors.ink,
          behavior: SnackBarBehavior.floating,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final savedAartis = ref.watch(userAartiProvider);

    return SafeArea(
      child: Column(
        children: [
          AartiAppBar(onMenuTap: widget.onOpenDrawer),
          Expanded(
            child: CustomScrollView(
              physics: const BouncingScrollPhysics(),
              slivers: [
          // Header
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(24, 24, 24, 0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('MY COLLECTION',
                      style:
                          AppTextStyles.label(size: 10, color: AppColors.ink3)),
                  const SizedBox(height: 6),
                  RichText(
                    text: TextSpan(
                      style: AppTextStyles.displayLarge(context).copyWith(
                        fontSize: 34,
                      ),
                      children: const [
                        TextSpan(text: 'Personal '),
                        TextSpan(
                          text: 'Collection',
                          style: TextStyle(
                            fontStyle: FontStyle.italic,
                            color: AppColors.saffron,
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    '${savedAartis.length} saved · Private to you',
                    style:
                        AppTextStyles.body(size: 13, color: AppColors.ink3),
                  ),
                ],
              ),
            ),
          ),

          // Add button / toggle form
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(24, 20, 24, 0),
              child: OutlinedButton.icon(
                onPressed: () {
                  if (_showForm) {
                    _clearForm();
                  }
                  setState(() => _showForm = !_showForm);
                },
                icon: Icon(
                  _showForm ? Icons.close : Icons.add_rounded,
                  size: 18,
                ),
                label: Text(_showForm
                    ? 'Cancel'
                    : (_editingId != null ? 'Editing Aarti' : 'Add New Aarti')),
                style: OutlinedButton.styleFrom(
                  foregroundColor: AppColors.saffron,
                  side: const BorderSide(color: AppColors.saffron),
                  minimumSize: const Size(double.infinity, 48),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14)),
                ),
              ),
            ),
          ),

          // Form (expandable)
          if (_showForm)
            SliverPadding(
              padding: const EdgeInsets.fromLTRB(24, 20, 24, 0),
              sliver: SliverList(
                delegate: SliverChildListDelegate([
                  _FormField(
                    label: 'Deity Name',
                    hint: 'e.g. Ganesha, Shiva, Lakshmi…',
                    controller: _deityCtrl,
                  ),
                  const SizedBox(height: 14),
                  _FormField(
                    label: 'Aarti Title (English)',
                    hint: 'e.g. Jai Ganesh Deva',
                    controller: _titleCtrl,
                  ),
                  const SizedBox(height: 14),
                  _FormField(
                    label: 'Title in Devanagari',
                    hint: 'e.g. जय गणेश देव',
                    controller: _devTitleCtrl,
                  ),
                  const SizedBox(height: 14),
                  _FormField(
                    label: 'Lyrics (Devanagari)',
                    hint:
                        'ॐ जय जगदीश हरे…\n\n(separate verses with a blank line)',
                    maxLines: 6,
                    controller: _lyricsCtrl,
                  ),
                  const SizedBox(height: 14),
                  _FormField(
                    label: 'Transliteration (Roman)',
                    hint:
                        'Om Jai Jagdish Hare…\n\n(match verse structure above)',
                    maxLines: 6,
                    controller: _translitCtrl,
                  ),
                  const SizedBox(height: 14),
                  _FormField(
                    label: 'Gujarati Script (Optional)',
                    hint:
                        'ૐ જય જગદીશ હરે…\n\n(match verse structure above)',
                    maxLines: 6,
                    controller: _gujaratiCtrl,
                  ),
                  const SizedBox(height: 14),
                  _FormField(
                    label: 'Festival Tags (comma separated)',
                    hint: 'e.g. Diwali, Navratri, Ganesh Chaturthi',
                    controller: _festivalTagsCtrl,
                  ),
                  const SizedBox(height: 18),
                  ElevatedButton.icon(
                    onPressed: _saveAarti,
                    icon: Icon(
                        _editingId != null
                            ? Icons.check_outlined
                            : Icons.save_outlined,
                        size: 16),
                    label: Text(_editingId != null
                        ? 'Update Aarti'
                        : 'Save to My Collection'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.ink,
                      foregroundColor: AppColors.white,
                      minimumSize: const Size(double.infinity, 52),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(14)),
                      textStyle: const TextStyle(
                          fontSize: 14, fontWeight: FontWeight.w400),
                      elevation: 0,
                    ),
                  ),
                ]),
              ),
            ),

          // Saved Collection List
          if (savedAartis.isEmpty && !_showForm)
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.all(48),
                child: Column(
                  children: [
                    Icon(Icons.library_music_outlined,
                        size: 48,
                        color: AppColors.ink3.withValues(alpha: 0.4)),
                    const SizedBox(height: 16),
                    Text(
                      'No saved Aartis yet',
                      style: AppTextStyles.serifBody(
                          size: 18, color: context.textPrimary),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'Tap "Add New Aarti" to create your\nfirst personal prayer.',
                      textAlign: TextAlign.center,
                      style: AppTextStyles.body(
                          size: 13, color: AppColors.ink3),
                    ),
                  ],
                ),
              ),
            ),

          if (savedAartis.isNotEmpty) ...[
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(24, 28, 24, 12),
                child: Text('SAVED AARTIS',
                    style:
                        AppTextStyles.label(size: 10, color: AppColors.ink3)),
              ),
            ),
            SliverPadding(
              padding: const EdgeInsets.fromLTRB(24, 0, 24, 60),
              sliver: SliverList(
                delegate: SliverChildBuilderDelegate(
                  (ctx, i) {
                    final aarti = savedAartis[i];
                    final isInPuja = ref.watch(
                        pujaOrderProvider.notifier).isInPuja(aarti.id);
                    return Padding(
                      padding: const EdgeInsets.only(bottom: 10),
                      child: _SavedAartiTile(
                        aarti: aarti,
                        isInPuja: isInPuja,
                        onTap: () => Navigator.push(
                          ctx,
                          MaterialPageRoute(
                            builder: (_) => AartiDetailScreen(aarti: aarti),
                          ),
                        ),
                        onEdit: () => _populateFormForEdit(aarti),
                        onTogglePuja: () {
                          if (isInPuja) {
                            ref.read(pujaOrderProvider.notifier)
                                .removeAarti(aarti.id);
                          } else {
                            ref.read(pujaOrderProvider.notifier)
                                .addAarti(aarti.id);
                          }
                        },
                        onDelete: () {
                          ref
                              .read(userAartiProvider.notifier)
                              .delete(aarti.id);
                        },
                      ),
                    );
                  },
                  childCount: savedAartis.length,
                ),
              ),
            ),
          ],
        ],
      ),
          ),
        ],
      ),
    );
  }
}

class _SavedAartiTile extends StatelessWidget {
  final AartiItem aarti;
  final bool isInPuja;
  final VoidCallback onTap;
  final VoidCallback onEdit;
  final VoidCallback onTogglePuja;
  final VoidCallback onDelete;

  const _SavedAartiTile({
    required this.aarti,
    required this.isInPuja,
    required this.onTap,
    required this.onEdit,
    required this.onTogglePuja,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: context.surface,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: context.border),
        ),
        child: Row(
          children: [
            Container(
              width: 40,
              height: 40,
              decoration: BoxDecoration(
                color: AppColors.saffronGlow,
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(Icons.music_note_outlined,
                  size: 18, color: AppColors.saffron),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(aarti.deity.toUpperCase(),
                      style:
                          AppTextStyles.label(size: 9, color: AppColors.saffron)),
                  const SizedBox(height: 1),
                  Text(aarti.title,
                      style: AppTextStyles.serifBody(
                          size: 15, color: context.textPrimary),
                      overflow: TextOverflow.ellipsis),
                  Text(aarti.devanagari,
                      style:
                          AppTextStyles.devanagari(size: 11, color: AppColors.ink3),
                      overflow: TextOverflow.ellipsis),
                  if (aarti.festivalTags.isNotEmpty)
                    Padding(
                      padding: const EdgeInsets.only(top: 4),
                      child: Wrap(
                        spacing: 4,
                        children: aarti.festivalTags
                            .take(3)
                            .map((t) => Container(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 6, vertical: 2),
                                  decoration: BoxDecoration(
                                    color: AppColors.saffronGlow,
                                    borderRadius: BorderRadius.circular(4),
                                  ),
                                  child: Text(t,
                                      style: AppTextStyles.body(
                                          size: 9,
                                          color: AppColors.saffronDark)),
                                ))
                            .toList(),
                      ),
                    ),
                ],
              ),
            ),
            Text(aarti.versesLabel,
                style: AppTextStyles.body(size: 11, color: AppColors.ink3)),
            const SizedBox(width: 6),
            GestureDetector(
              onTap: onEdit,
              child: Container(
                width: 28,
                height: 28,
                decoration: BoxDecoration(
                  color: context.border,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Icon(Icons.edit_outlined,
                    size: 14, color: AppColors.ink3),
              ),
            ),
            const SizedBox(width: 6),
            GestureDetector(
              onTap: onTogglePuja,
              child: Container(
                width: 28,
                height: 28,
                decoration: BoxDecoration(
                  color: isInPuja ? AppColors.saffronGlow : context.border,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  isInPuja
                      ? Icons.auto_awesome
                      : Icons.auto_awesome_outlined,
                  size: 14,
                  color: isInPuja ? AppColors.saffron : AppColors.ink3,
                ),
              ),
            ),
            const SizedBox(width: 6),
            GestureDetector(
              onTap: onDelete,
              child: Container(
                width: 28,
                height: 28,
                decoration: BoxDecoration(
                  color: context.border,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Icon(Icons.delete_outline,
                    size: 14, color: AppColors.ink3),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _FormField extends StatelessWidget {
  final String label;
  final String hint;
  final int maxLines;
  final TextEditingController? controller;

  const _FormField({
    required this.label,
    required this.hint,
    this.maxLines = 1,
    this.controller,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label.toUpperCase(),
            style: AppTextStyles.label(size: 10, color: AppColors.ink3)),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          maxLines: maxLines,
          style: AppTextStyles.body(size: 14, color: context.textPrimary),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: AppTextStyles.body(size: 14, color: AppColors.ink3),
            filled: true,
            fillColor: context.surface,
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: context.borderSubtle),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: context.borderSubtle),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide:
                  const BorderSide(color: AppColors.saffron, width: 1.5),
            ),
          ),
        ),
      ],
    );
  }
}
